{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "848edd9c-6088-4e22-82a9-248d1e16bc4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import pyarrow\n",
    "from pybroker import Alpaca\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c9cbb2f6-6d13-4fd9-85e9-49d96f780c31",
   "metadata": {},
   "outputs": [],
   "source": [
    "alpaca = Alpaca(os.environ['ALPACA_API_KEY'], os.environ['ALPACA_SECRET_KEY'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "832ba1db-5baf-4c60-aa28-fea4255d5e71",
   "metadata": {},
   "outputs": [],
   "source": [
    " #Reads and cleans the composition file\n",
    "\n",
    "def load_sp500_components(path):\n",
    "    df = pd.read_csv(path, sep=\",\")\n",
    "    df[\"tickers_list\"] = df[\"tickers\"].str.split(\",\")\n",
    "    df = df.explode(\"tickers_list\")\n",
    "    df[\"tickers_list\"] = df[\"tickers_list\"].str.strip()\n",
    "\n",
    "    return df[[\"date\", \"tickers\"]].dropna().reset_index(drop=True)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f241d6a5-25b7-4568-b19e-a142ad6020d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Creates daily components list\n",
    "def build_daily_components(df):\n",
    "    # 1. Parse date\n",
    "    df[\"date\"] = pd.to_datetime(df[\"date\"], dayfirst=True)\n",
    "\n",
    "    # 2. Ordina\n",
    "    df = df.sort_values(\"date\")\n",
    "\n",
    "    # 3. Crea calendario continuo\n",
    "    all_days = pd.date_range(\n",
    "        start=df[\"date\"].min(),\n",
    "        end=df[\"date\"].max(),\n",
    "        freq=\"D\"\n",
    "    )\n",
    "    calendar = pd.DataFrame({\"date\": all_days})\n",
    "\n",
    "    # 4. Raggruppa tickers per data (come prima)\n",
    "    grouped = df.groupby(\"date\")[\"tickers\"].apply(list).reset_index(name=\"tickers\")\n",
    "\n",
    "    # 5. Merge-asof backward per riempire i buchi\n",
    "    daily_comp = pd.merge_asof(\n",
    "        calendar,\n",
    "        grouped.sort_values(\"date\"),\n",
    "        on=\"date\",\n",
    "        direction=\"backward\"\n",
    "    )\n",
    "\n",
    "    return daily_comp\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "4aec22eb-9d3b-409a-b14d-87a76fb618ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import pandas as pd\n",
    "\n",
    "def download_hf_data(daily_comp, start_date, end_date, timeframe=\"1m\", block_days=7):\n",
    "    \"\"\"\n",
    "    Download high-frequency Alpaca data for all S&P500 components\n",
    "    appearing in daily_comp between start_date and end_date.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    daily_comp : DataFrame\n",
    "        Must contain columns: [\"date\", \"tickers\"] where tickers is a list.\n",
    "    start_date : str or Timestamp\n",
    "    end_date   : str or Timestamp\n",
    "    timeframe  : str\n",
    "        e.g. \"1m\", \"5m\", \"1h\"\n",
    "    block_days : int\n",
    "        Size of each download block (default 30 days)\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    DataFrame\n",
    "        Concatenated HF data for all blocks.\n",
    "    \"\"\"\n",
    "\n",
    "    # 1. Convert date column\n",
    "   daily_comp[\"date\"] = pd.to_datetime(daily_comp[\"date\"], format=\"%m/%d/%Y\")\n",
    "\n",
    "    # 2. Filter global range\n",
    "    start_global = pd.Timestamp(start_date)\n",
    "    end_global   = pd.Timestamp(end_date)\n",
    "\n",
    "    daily_filtered = daily_comp[\n",
    "        (daily_comp[\"date\"] >= start_global) &\n",
    "        (daily_comp[\"date\"] < end_global)\n",
    "    ]\n",
    "\n",
    "    # 3. Extract sorted list of unique dates\n",
    "    dates = daily_filtered[\"date\"].sort_values().to_list()\n",
    "\n",
    "    all_dfs = []\n",
    "    n = len(dates)\n",
    "\n",
    "    # 4. Loop over blocks\n",
    "    for i in range(0, n, block_days):\n",
    "        start = dates[i]\n",
    "        end = start + pd.Timedelta(days=block_days)\n",
    "\n",
    "        # Select block\n",
    "        block = daily_filtered[\n",
    "            (daily_filtered[\"date\"] >= start) &\n",
    "            (daily_filtered[\"date\"] < end)\n",
    "        ]\n",
    "\n",
    "        if block.empty:\n",
    "            print(f\"[INFO] No data in block {start.date()} → {end.date()}, skipped.\")\n",
    "            continue\n",
    "\n",
    "        # Extract tickers for this block\n",
    "        tickers_block = list(map(str, sorted(set().union(*block[\"tickers\"]))))\n",
    "\n",
    "\n",
    "        print(f\"\\n[INFO] Downloading {len(tickers_block)} tickers | {start.date()} → {end.date()}\")\n",
    "        \n",
    "\n",
    "\n",
    "        # Time the API call\n",
    "        t0 = time.time()\n",
    "\n",
    "        df = alpaca.query(\n",
    "            tickers_block,\n",
    "            start_date=start,\n",
    "            end_date=end,\n",
    "            timeframe=timeframe\n",
    "        )\n",
    "\n",
    "        elapsed = time.time() - t0\n",
    "        print(f\"[INFO] → Received {len(df)} rows in {elapsed:.2f} seconds\")\n",
    "\n",
    "        df[\"block_start\"] = start\n",
    "        all_dfs.append(df)\n",
    "\n",
    "    # 5. Final concatenation\n",
    "    full_df = pd.concat(all_dfs, ignore_index=True)\n",
    "\n",
    "    return full_df\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "   \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "043743b3-132d-440d-a12b-34382cfee6a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "df= load_sp500_components(\"S&P 500 Historical Components & Changes(11-16-2025).csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "06797884-8ddc-4136-8944-2d6df187c873",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>tickers</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>02/01/1996</td>\n",
       "      <td>AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>02/01/1996</td>\n",
       "      <td>AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>02/01/1996</td>\n",
       "      <td>AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>02/01/1996</td>\n",
       "      <td>AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>02/01/1996</td>\n",
       "      <td>AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1341690</th>\n",
       "      <td>11/11/2025</td>\n",
       "      <td>A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1341691</th>\n",
       "      <td>11/11/2025</td>\n",
       "      <td>A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1341692</th>\n",
       "      <td>11/11/2025</td>\n",
       "      <td>A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1341693</th>\n",
       "      <td>11/11/2025</td>\n",
       "      <td>A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1341694</th>\n",
       "      <td>11/11/2025</td>\n",
       "      <td>A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1341695 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "               date                                            tickers\n",
       "0        02/01/1996  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...\n",
       "1        02/01/1996  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...\n",
       "2        02/01/1996  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...\n",
       "3        02/01/1996  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...\n",
       "4        02/01/1996  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...\n",
       "...             ...                                                ...\n",
       "1341690  11/11/2025  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...\n",
       "1341691  11/11/2025  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...\n",
       "1341692  11/11/2025  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...\n",
       "1341693  11/11/2025  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...\n",
       "1341694  11/11/2025  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...\n",
       "\n",
       "[1341695 rows x 2 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "65234ded-5584-4b61-b7d5-5e4df56f12c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2= build_daily_components(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7127c83b-6a2f-436a-b115-7cc300be61a5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>tickers</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1996-01-02</td>\n",
       "      <td>[AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1996-01-03</td>\n",
       "      <td>[AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1996-01-04</td>\n",
       "      <td>[AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1996-01-05</td>\n",
       "      <td>[AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1996-01-06</td>\n",
       "      <td>[AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10902</th>\n",
       "      <td>2025-11-07</td>\n",
       "      <td>[A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10903</th>\n",
       "      <td>2025-11-08</td>\n",
       "      <td>[A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10904</th>\n",
       "      <td>2025-11-09</td>\n",
       "      <td>[A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10905</th>\n",
       "      <td>2025-11-10</td>\n",
       "      <td>[A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10906</th>\n",
       "      <td>2025-11-11</td>\n",
       "      <td>[A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>10907 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            date                                            tickers\n",
       "0     1996-01-02  [AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...\n",
       "1     1996-01-03  [AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...\n",
       "2     1996-01-04  [AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...\n",
       "3     1996-01-05  [AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...\n",
       "4     1996-01-06  [AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,A...\n",
       "...          ...                                                ...\n",
       "10902 2025-11-07  [A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...\n",
       "10903 2025-11-08  [A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...\n",
       "10904 2025-11-09  [A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...\n",
       "10905 2025-11-10  [A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...\n",
       "10906 2025-11-11  [A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,AD...\n",
       "\n",
       "[10907 rows x 2 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "723aa5bd-a0cd-44fd-bbd5-779c60f1e761",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "count    10907.000000\n",
      "mean       498.158797\n",
      "std          5.376602\n",
      "min        487.000000\n",
      "25%        495.000000\n",
      "50%        497.000000\n",
      "75%        503.000000\n",
      "max        507.000000\n",
      "Name: tickers, dtype: float64\n"
     ]
    }
   ],
   "source": [
    "lengths=df2[\"tickers\"].apply(len)\n",
    "\n",
    "print(lengths.describe())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da3d0958-7007-475b-a8d0-ed9e378331ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "mask_few = lengths < 488\n",
    "df2.loc[mask_few, [\"date\", \"tickers\"]].head().describe()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "85296cf7-39f3-428f-8216-b0261109c636",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "[INFO] Downloading 1 tickers | 2025-01-02 → 2025-01-09\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:29 \n",
      "\n",
      "[INFO] → Received 953079 rows in 88.90 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-01-09 → 2025-01-16\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:15 \n",
      "\n",
      "[INFO] → Received 782121 rows in 74.83 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-01-16 → 2025-01-23\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:13 \n",
      "\n",
      "[INFO] → Received 784154 rows in 73.19 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-01-23 → 2025-01-30\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:14 \n",
      "\n",
      "[INFO] → Received 982306 rows in 73.64 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-01-30 → 2025-02-06\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:13 \n",
      "\n",
      "[INFO] → Received 995112 rows in 73.32 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-02-06 → 2025-02-13\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:13 \n",
      "\n",
      "[INFO] → Received 975181 rows in 72.73 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-02-13 → 2025-02-20\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:01 \n",
      "\n",
      "[INFO] → Received 780902 rows in 61.23 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-02-20 → 2025-02-27\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:16 \n",
      "\n",
      "[INFO] → Received 985638 rows in 75.88 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-02-27 → 2025-03-06\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:31 \n",
      "\n",
      "[INFO] → Received 1001060 rows in 91.08 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-03-06 → 2025-03-13\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:23 \n",
      "\n",
      "[INFO] → Received 1014288 rows in 83.10 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-03-13 → 2025-03-20\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:12 \n",
      "\n",
      "[INFO] → Received 964907 rows in 72.11 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-03-20 → 2025-03-27\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:10 \n",
      "\n",
      "[INFO] → Received 958157 rows in 69.64 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-03-27 → 2025-04-03\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:25 \n",
      "\n",
      "[INFO] → Received 970027 rows in 85.01 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-04-03 → 2025-04-10\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:20 \n",
      "\n",
      "[INFO] → Received 1076944 rows in 80.22 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-04-10 → 2025-04-17\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:14 \n",
      "\n",
      "[INFO] → Received 996231 rows in 73.57 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-04-17 → 2025-04-24\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:00:58 \n",
      "\n",
      "[INFO] → Received 790933 rows in 58.35 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-04-24 → 2025-05-01\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:13 \n",
      "\n",
      "[INFO] → Received 977503 rows in 73.18 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-05-01 → 2025-05-08\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 974722 rows in 71.47 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-05-08 → 2025-05-15\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:19 \n",
      "\n",
      "[INFO] → Received 985927 rows in 78.63 seconds\n",
      "\n",
      "[INFO] Downloading 2 tickers | 2025-05-15 → 2025-05-22\n",
      "Tickers nel blocco: 2\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:12 \n",
      "\n",
      "[INFO] → Received 964762 rows in 72.31 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-05-22 → 2025-05-29\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:00:56 \n",
      "\n",
      "[INFO] → Received 771067 rows in 56.47 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-05-29 → 2025-06-05\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:12 \n",
      "\n",
      "[INFO] → Received 962609 rows in 72.30 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-06-05 → 2025-06-12\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:10 \n",
      "\n",
      "[INFO] → Received 950626 rows in 69.96 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-06-12 → 2025-06-19\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 965776 rows in 70.57 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-06-19 → 2025-06-26\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:01 \n",
      "\n",
      "[INFO] → Received 776108 rows in 60.60 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-06-26 → 2025-07-03\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:12 \n",
      "\n",
      "[INFO] → Received 970745 rows in 71.86 seconds\n",
      "\n",
      "[INFO] Downloading 2 tickers | 2025-07-03 → 2025-07-10\n",
      "Tickers nel blocco: 2\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:00:50 \n",
      "\n",
      "[INFO] → Received 686398 rows in 49.69 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-07-10 → 2025-07-17\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:10 \n",
      "\n",
      "[INFO] → Received 958227 rows in 70.12 seconds\n",
      "\n",
      "[INFO] Downloading 3 tickers | 2025-07-17 → 2025-07-24\n",
      "Tickers nel blocco: 3\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 973537 rows in 71.37 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-07-24 → 2025-07-31\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 978846 rows in 70.78 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-07-31 → 2025-08-07\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:14 \n",
      "\n",
      "[INFO] → Received 1001418 rows in 73.59 seconds\n",
      "\n",
      "[INFO] Downloading 2 tickers | 2025-08-07 → 2025-08-14\n",
      "Tickers nel blocco: 2\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 970391 rows in 70.78 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-08-14 → 2025-08-21\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:10 \n",
      "\n",
      "[INFO] → Received 957251 rows in 69.93 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-08-21 → 2025-08-28\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:07 \n",
      "\n",
      "[INFO] → Received 940447 rows in 67.12 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-08-28 → 2025-09-04\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:00:56 \n",
      "\n",
      "[INFO] → Received 760120 rows in 55.54 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-09-04 → 2025-09-11\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:09 \n",
      "\n",
      "[INFO] → Received 960923 rows in 69.45 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-09-11 → 2025-09-18\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:22 \n",
      "\n",
      "[INFO] → Received 966516 rows in 82.31 seconds\n",
      "\n",
      "[INFO] Downloading 2 tickers | 2025-09-18 → 2025-09-25\n",
      "Tickers nel blocco: 2\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:18 \n",
      "\n",
      "[INFO] → Received 980764 rows in 78.14 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-09-25 → 2025-10-02\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 973447 rows in 71.24 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-10-02 → 2025-10-09\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:10 \n",
      "\n",
      "[INFO] → Received 969292 rows in 69.71 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-10-09 → 2025-10-16\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:12 \n",
      "\n",
      "[INFO] → Received 985495 rows in 71.64 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-10-16 → 2025-10-23\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:11 \n",
      "\n",
      "[INFO] → Received 973563 rows in 71.45 seconds\n",
      "\n",
      "[INFO] Downloading 1 tickers | 2025-10-23 → 2025-10-30\n",
      "Tickers nel blocco: 1\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:13 \n",
      "\n",
      "[INFO] → Received 990009 rows in 72.90 seconds\n",
      "\n",
      "[INFO] Downloading 4 tickers | 2025-10-30 → 2025-11-06\n",
      "Tickers nel blocco: 4\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:17 \n",
      "\n",
      "[INFO] → Received 1043625 rows in 77.48 seconds\n",
      "\n",
      "[INFO] Downloading 2 tickers | 2025-11-06 → 2025-11-13\n",
      "Tickers nel blocco: 2\n",
      "Loading bar data...\n",
      "Loaded bar data: 0:01:21 \n",
      "\n",
      "[INFO] → Received 1029706 rows in 81.28 seconds\n"
     ]
    }
   ],
   "source": [
    "full_df = download_hf_data(\n",
    "    df2,\n",
    "    start_date=\"2025-01-02\",\n",
    "    end_date=\"2025-12-31\",\n",
    "    timeframe=\"1m\",\n",
    "    block_days=7\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "9d4cb2dc-1136-47bc-9a13-77da88adefab",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "487"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(df2[\"tickers\"][0])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
